name: "@holochain/hc-seed-bundle Test"
on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          registry-url: 'https://registry.npmjs.org'
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - run: bun test
